Portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]
# urlpatterns += i18n_patterns(
#     path('', include('basic.urls')),
# )

news/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', cache_page(60)(PostsList.as_view()), name='posts_list'),
    path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('search/', SearchPosts.as_view(), name='search_posts'),
    path('search/posts/', views.Search.as_view(), name='search'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', NewsUpdate.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/create/', ArticleCreate.as_view(), name='article_create'),
    path('articles/<int:pk>/edit/', ArticleUpdate.as_view(), name='article_update'),
    path('articles/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    path("categories/<int:pk>", CategoriesView.as_view(), name='categories_list'),
    path('categories/<int:pk>/subscribe/', add_me_to_category, name='sub_category'),
    path('categories/<int:pk>/unsubscribe/', delete_me_to_category, name='un_sub_category'),
    path('categories/', cache_page(60 * 5)(CategoryListView.as_view()), name='category_lists'),
]

news/models.py
from django.shortcuts import render
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    """ Модель описывает Автора """
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Автор')
    rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг автора')

    def __repr__(self):
        return f"Author (user.name='{self.user}', rating='{self.rating}')"

    def __str__(self):
        return f"{self.user}"

    def update_rating(self):
        """
            суммарный рейтинг каждой статьи автора умножается на 3;
            суммарный рейтинг всех комментариев автора;
            суммарный рейтинг всех комментариев к статьям автора.
        """
        posts_rating = self.posts.aggregate(result=Sum('rating')).get('result')
        comments_rating = self.user.comments.aggregate(result=Sum('rating')).get('result')
        print(f"===== {self.user}: обновляем рейтинг автора =====")
        print(f"Рейтинг постов = {posts_rating}")
        print(f"Рейтинг комментов = {comments_rating}")
        self.rating = 3 * posts_rating + comments_rating
        self.save()
        print(f"Рейтинг = 3 * {posts_rating} + {comments_rating} = {self.rating}")

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Category(models.Model):
    """ Категории новостей / статей — темы, которые
        они отражают(спорт, политика, образование и т.д.).
        Здесь категории, то же что тэги. Их можно добавлять любое количество."""
    name = models.CharField(unique=True, max_length=128, verbose_name='Название категории')
    """ Подписаться на рассылку """
    subscribers = models.ManyToManyField(User, related_name='categories', verbose_name='Подписчики')

    def __repr__(self):
        return f"Category (name='{self.name}')"

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Post(models.Model):
    """ Модель содержит в себе статьи и новости, которые создают пользователи.
        Каждый объект может иметь одну или несколько категорий. """
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOISES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания поста')
    post_type = models.CharField(max_length=2, choices=CATEGORY_CHOISES, default=ARTICLE, verbose_name='Тип поста')
    category = models.ManyToManyField(Category, through="PostCategory", verbose_name='Категория поста')
    title = models.CharField(max_length=128, verbose_name='Название поста')
    text = models.TextField(verbose_name='Текст поста')
    rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг поста')

    def __repr__(self):
        return f"Post (author.user.name='{self.author.user}', title='{self.title}', rating='{self.rating}'," \
               f"post_type='{self.post_type}')"

    def like(self):
        """ Увеличить на единицу значение 'Post.rating'. """
        self.rating += 1
        self.save()

    def dislike(self):
        """ Уменьшить на единицу значение 'Post.rating'. """
        self.rating -= 1
        self.save()

    def preview(self, length=124) -> str:
        """ Вернуть превью статьи. """
        return f"{self.text[:length]}..." if len(self.text) > length else self.text

    def __str__(self):
        """ Отображение названия поста и краткого текста поста """
        return f'{self.title.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        """ Вернуть url, зарегистрированный для отображения одиночного товара """
        return reverse('post_detail', args=[str(self.id)])

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"


class PostCategory(models.Model):
    """ Промежуточная модель для связи «многие ко многим». """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    def __str__(self):
        return f'{self.post.title} | {self.category.name}'

    class Meta:
        verbose_name = "Пост с категориями"
        verbose_name_plural = "Посты с категориями"


class Comment(models.Model):
    """ Под каждой новостью/статьёй можно оставлять комментарии. """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Текст комментария')
    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг комментария')

    def like(self):
        """ Увеличить на единицу значение 'Comment.rating'. """
        self.rating += 1
        self.save()

    def dislike(self):
        """ Уменьшить на единицу значение 'Comment.rating'. """
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'ID comment: {self.id}'

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

templates/account_update_user.html
{% extends 'default.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{% block title %} Изменить профиль {% endblock %}
{% if is_your_id == path %}
{% else %}
<meta http-equiv="refresh" content="5; url={% url 'account_update' is_your_id %}">
{% endif %}
{% endblock %}

{% block content %}

<hr>

{% if is_your_id == path %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-outline-secondary " type="submit" value="Сохранить">
</form>
{% else %}
<h2><a href="{% url 'account_update' is_your_id %}">Вы пытаетесь изменить чужой профиль. Нажмите, чтобы вернуться к изменениям своего профиля.
Или в течение 5 секунд мы сделаем это автоматически</a></h2>
{% endif %}

<hr>

{% if is_not_author %}
<h4>Хотите стать автором и публиковать статьи?</h4>
<a class="btn btn-outline-secondary" type="submit" href="{% url 'set_me_author' %}">нажав сюда я стану автором</a><br><br>
{% endif %}

{% endblock %}

templates/base.html
<!doctype  html>
<html  lang="en">
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"><title>Аутентификация</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">Аутентификация</h1>
      {% block main %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/default.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock %}</title>
        <!-- Favicon-->
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: #2f353b;
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      .dropdown:hover > .dropdown-menu {
          display: block;

      }
      .fa_custom {
      color: #0099CC
      }
    </style>
    </head>
    <body>
    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="home" viewBox="0 0 16 16">
    <title>Домой</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
</svg>
        <!-- Responsive navbar-->
  <div class="b-example-divider"></div>

  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/news/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#home"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <!-- Кнопка-триггер модального окна -->
            <a class="nav-link px-2 text-white" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Выйти
            </a>

            <!-- Модальное окно -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title text-black" id="exampleModalLabel">Вы уверены, что хотите выйти?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                  </div>
                  <div class="modal-body text-black">
                    desgsdfgsdfgsdfgsdfgsdfgsdfg
                  </div>
                  <div class="modal-footer text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>

                    <a type="button" class="btn btn-primary" href={% url 'account_logout' %} >Выйти</a>
                  </div>
                </div>
              </div>
            </div>
{#          <li><a href="#" class="nav-link px-2 text-secondary" data-bs-placement="bottom" title="Подсказка внизу">Home</a></li>#}
          <li><a href="/contact/" class="nav-link px-2 text-white" data-bs-placement="bottom" title="Подсказка внизу">Контакты</a></li>
            <a class="nav-link px-2 text-white" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Кнопка
            </a>
          <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title text-black" id="offcanvasExampleLabel">Вне холста</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
              </div>
              <div class="offcanvas-body text-black">
                <div>
                  Какой-то текст в качестве заполнителя. В реальной жизни у вас могут быть элементы, которые Вы выбрали. Нравится, текст, изображения, списки и т. д.
                </div>
                <div class="dropdown mt-3">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton">
                    Кнопка раскрывающегося списка
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="#">Действие</a></li>
                    <li><a class="dropdown-item" href="#">Другое действие</a></li>
                    <li><a class="dropdown-item" href="#">Что-то еще здесь</a></li>
                  </ul>
                </div>
              </div>
          </div>
          <li><a href="#" class="nav-link px-2 text-white" data-bs-toggle="offcanvas" aria-controls="offcanvasExample" data-bs-placement="bottom" title="Подсказка внизу">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white" data-bs-placement="bottom" title="Часто задаваемые вопросы">FAQs</a></li>
          <li><a href="/about/" class="nav-link px-2 text-white" data-bs-placement="bottom" title="О нас">О нас</a></li>
          {% if user.is_superuser %}
          <li><a href="/admin/" class="nav-link px-2 text-white" data-bs-placement="bottom" title="Админка">Админка</a></li>
          {% endif %}
          <div class="dropdown">
              <a class="nav-link px-2 text-white dropdown-toggle" href="" id="dropdownMenuLink" data-bs-placement="bottom" aria-expanded="false">Меню</a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'search_posts' %}">Поиск статей</a></li>
                <li><a class="dropdown-item" href="/news/articles/create/">Добавить материал</a></li>
                <li><a class="dropdown-item" href="{% url 'category_lists' %}">Новости по категориям</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="/news/articles/create/">Добавить материал</a></li>
              </ul>
          </div>
        </ul>

        <form action="{% url 'search' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 d-flex editContent " role="search">
            <input type="search" class="form-control form-control-dark text-bg-dark" name="q" required="" placeholder="Поиск в тексте..." aria-label="Search">
            <button class="btn btn-outline-secondary me-10" type="submit">Поиск</button>
{#                <span class="fa fa-search" ></span>#}
        </form>

        <div class="text-end">
          {% if user.is_anonymous %}
          <a type="button" class="btn btn-outline-light me-2" href="/accounts/login/">Войти</a>
          <a type="button" class="btn btn-warning" href="/accounts/signup/">Регистрация</a>
          {% endif %}
          {% if user.is_authenticated %}
          <a type="button" class="btn btn-outline-light me-2" href="/accounts/logout/">Выйти</a>
          <a type="button" class="btn btn-outline-light me-2" href="/accounts/update/{{ user.pk }}">Твой профиль {{ user.username }}</a>
          {% endif %}
        </div>
      </div>
    </div>
  </header>
        <div class="col-lg-12 text-center">
     {% if user.is_authenticated %}
        <p>Привет {{ user.username }}!</p>
     {% else %}
        <p>Вы не вошли в систему.</p>
        <a class="btn btn-outline-secondary " href="{% url 'account_login' %}">Войти</a>
     {% endif %}
     </div>
        <!-- Page content-->
<div class="container">
   <div class="row">
       <div class="col-lg-12 text-center">
           {% block content %}
           {{ flatpage.content }}
           {% endblock content %}
       </div>
   </div>
</div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Portal 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="/static/bootstrap/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

templates/post_created_email.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Привет, вышла новая статья в категории, на которую ты подписан! <a href="{{ link }}">Вот она!</a></h2>
<p>{{text}}</p>
</body>
</html>

templates/post_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем запись с заголовком "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" class="btn btn-danger"/>
    <a class="btn btn-secondary" role="button" href="{{ previous_page_url }}">Отмена</a>
</form>
{% endblock content %}

templates/post_search.html
{% extends 'default.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Поиск новости или статьи
{% endblock title %}

<!-- В контенте на странице выводим форму поиска постов. -->
{% block content %}

{# Форма фильтра 'PostFilter' #}
    <form action="" method="GET">
        {# Переменная, которую мы передали через контекст, может сгенерировать форму с полями #}
        {{ search_filter.form|crispy }}
        <input type="submit" value="Найти" class="btn btn-secondary"/>
        <a class="btn btn-secondary" role="button" href="{{ request.path }}">Сбросить фильтры</a>
    </form>

<div class="col-lg-12 text-center">
    <h1>Все посты</h1>
    <h3>Всего постов: {{ posts|length }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Автор</th>
            <th scope="col">Категория</th>
            <th scope="col">Дата публикации</th>
            <th scope="col">Текст</th>
            <th scope="col">Ссылка на статью</th>
            {% if perms.news.change_post or perms.news.delete_post %}
            <th scope="col">Редактировать</th>
            <th scope="col">Удалить</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row"><a href="{% url 'post_detail' post.pk %}"> {{ post.title|default:"Без заголовка" }} </th>
            <td>{{ post.author }}</td>
            <th scope="row">{% for category in post.category.all %}<a href="{% url 'categories_list' category.pk %}"> {{ category }}{% endfor %} </th>
            <td>{{ post.date_time }}</td>
            <td>{{ post.text | truncatewords:20 | censor | safe }}</td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/">Читать</a></td>
            {% if perms.news.change_post %}
            <td><a class="btn btn-primary btn-sm" href="/news/news/{{ post.pk }}/edit/">Редактировать</a></td>
            {% endif %}
            {% if perms.news.delete_post %}
            <td><a class="btn btn-primary btn-sm" href="/news/news/{{ post.pk }}/delete/">Удалить</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{# Пагинация на странице #}
<hr class="mt-4">

<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=1 %}">1</a></li>
                {% if page_obj.previous_page_number != 1 %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
               {% endif %}
            {% endif %}

            <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
               {% endif %}
                {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}

templates/posts_list.html
{% extends 'default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}
Посты
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
<div class="col-lg-12 text-center">
    <h1>Все посты</h1>
    <h3>Всего постов: {{ posts|length }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Автор</th>
            <th scope="col">Категория</th>
            <th scope="col">Дата публикации</th>
            <th scope="col">Текст</th>
            <th scope="col">Ссылка на статью</th>
            {% if perms.news.change_post or perms.news.delete_post %}
            <th scope="col">Редактировать</th>
            <th scope="col">Удалить</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row"><a href="{% url 'post_detail' post.pk %}">{{ post.title|default:"Без заголовка" }}</th>
            <td>{{ post.author }}</td>
            <th scope="row">{% for category in post.category.all %}<a href="{% url 'categories_list' category.pk %}"> {{ category }}{% endfor %} </th>
            <td>{{ post.date_time }}</td>
            <td>{{ post.text | truncatewords:20 | censor| safe}}</td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/">Читать</a></td>
            {% if perms.news.change_post %}
            <td><a class="btn btn-primary btn-sm" href="/news/news/{{ post.pk }}/edit/">Редактировать</a></td>
            {% endif %}
            {% if perms.news.delete_post %}
            <td><a class="btn btn-primary btn-sm" href="/news/news/{{ post.pk }}/delete/">Удалить</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{# Пагинация на странице #}
<hr class="mt-4">

<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=1 %}">1</a></li>
                {% if page_obj.previous_page_number != 1 %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
               {% endif %}
            {% endif %}

            <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{{ q }}{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
               {% endif %}
                {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}